NR-707 - golden metrics in observability panel
TeamCodeStream/codestream pull request #1046
Opened 2022-07-08 17:21 UTC by eric-j

2022-07-11 17:09 UTC, bcanzanella commented on shared/agent/src/providers/newrelic.ts
> +				newRelicAlertSeverity: entity.alertSeverity || "hi",
"hi"

2022-07-11 17:16 UTC, bcanzanella commented on shared/ui/Stream/Observability.tsx
> +																						url: newRelicUrl || " "
if there's no `newRelicUrl` perhaps this external link icon should be hidden?

2022-07-11 17:44 UTC, bcanzanella requested changes
looks good, couple small comments.

2022-07-15 14:21 UTC, eric-j commented
@bcanzanella I updated those requested changes

2022-07-15 15:46 UTC, bcanzanella commented on shared/ui/Stream/Observability.tsx
> +	}, 60000);
also, i don't believe i saw anything below, but i think working in some kind of lastUpdated value would be useful for the end users. perhaps it's in a tooltip or somewhere out of the way? That would let the user know that we're getting fresh stats. thoughts?

2022-07-15 20:46 UTC, merged