webview to agent migration of repo not found check logic + unit tests
TeamCodeStream/codestream pull request #1217
Opened 2022-10-13 20:35 UTC by eric-j

2022-10-13 22:00 UTC, dsellarsnr commented on shared/agent/src/providers/github.ts
>  				);
Too verbose need to remove or make debug

2022-10-13 22:47 UTC, eric-j commented on shared/agent/src/providers/github.ts
>  				);
Whoops, not supposed to be there

2022-10-13 22:54 UTC, dsellarsnr commented on shared/agent/src/providers/github.ts
>  				);
There are a few here and there

2022-10-13 23:10 UTC, dsellarsnr commented on shared/agent/src/providers/thirdPartyIssueProviderBase.ts
> +		repos: any;
Should be able to get rid of all the `any` in this function - this one is `CSRepository[]` and gives a type to most of the body - and error looks like it is a `string`

2022-10-13 23:18 UTC, dsellarsnr commented on shared/ui/store/providerPullRequests/slice.ts
>  export const getProviderPullRequestRepoObjectCore = (
I would nuke it, it is in git history. We will never forget about this method.

2022-10-13 23:19 UTC, dsellarsnr commented on shared/ui/Stream/PullRequests/Bitbucket/PullRequest.tsx
> +			prRepoId: currentPullRequest?.conversations?.repository?.prRepoId,
remove

2022-10-13 23:26 UTC, dsellarsnr requested changes
Looking good, just a few small changes.

2022-10-17 14:41 UTC, bcanzanella commented on shared/ui/store/providerPullRequests/slice.ts
>  export const getProviderPullRequestRepoObjectCore = (
+1

2022-10-17 14:45 UTC, bcanzanella commented on shared/agent/test/unit/providers/provider.spec.ts
> +	it("gh getProviderRepo url found match", async () => {
huge win here for something that has been a problem for a long while!

2022-10-18 17:22 UTC, dsellarsnr approved these changes

2022-10-18 22:46 UTC, dsellarsnr commented on shared/ui/src/__tests__/providerPullRequests/reducer.test.ts
>  interface RepoStub extends Omit<Partial<CSRepository>, "remotes"> {
Need to remove this whole file to get tests to pass (see vscode in teamcity)

2022-10-21 20:01 UTC, merged