Feature/common utils rebase
TeamCodeStream/codestream pull request #1299
Opened 2023-01-03 16:50 UTC by dsellarsnr

* No more symlinks, shared code resolved via relative paths
* Eliminate some of the duplicate code - shared date. iterable, searchTree, string now resolved via relative path and path aliases. 
* Add shell script utility to root (more robustness and documentation coming later)

2023-01-04 18:48 UTC, bcanzanella commented on shared/agent/src/agent.ts
> +import * as NewRelic from "newrelic";
can this line stay as the first import? IIRC the NR agent requires that.

2023-01-04 19:33 UTC, bcanzanella commented on shared/util/jest.global.js
> +	process.env.NEW_RELIC_ENABLED = "false";
nice

2023-01-04 19:41 UTC, bcanzanella requested changes
1 comment w/r/t imports

2023-01-09 17:49 UTC, dsellarsnr commented on shared/agent/src/agent.ts
> +import * as NewRelic from "newrelic";
fixed

2023-01-09 18:02 UTC, bcanzanella approved these changes

2023-01-09 18:24 UTC, merged