Feature/bitbucket
TeamCodeStream/codestream pull request #1437
Opened 2023-04-18 18:42 UTC by reneelpetit

adding in bitbucket functionality

2023-04-20 19:04 UTC, purplexa reviewed
looks pretty good to me, there are a few things that could be improved but most of it seems reasonable

2023-04-20 21:16 UTC, reneelpetit commented on shared/agent/src/providers/bitbucket.ts
> +		const response = array.map(item => {
So instead of all this
 `author: {
					avatarUrl: item.author.links.avatar.href,
					login: item.author.display_name,
				},
				baseRefName: item.destination.branch.name,
				body: item.summary.html,
				bodyText: item.summary.raw,
				createdAt: new Date(item.created_on).getTime(),
				headRefName: item.source.branch.name,
				headRepository: {
					name: item.source.repository.name,
					nameWithOwner: item.source.repository.full_name,
				},
				id: item.id + "",
				idComputed: JSON.stringify({
					id: item.id,
					pullRequestId: item.id,
					repoWithOwner: item.source.repository.full_name,
				}),
				lastEditedAt: item.updated_on,
				labels: {
					nodes: [],
				},
				number: item.id,
				providerId: providerId,
				state: item.state,
				title: item.title,
				updatedAt: item.updated_on,
				url: item.links.html.href,`

I would just use `...`  ?  Is that what you mean?

2023-04-20 21:26 UTC, purplexa commented on shared/agent/src/providers/bitbucket.ts
> +		const response = array.map(item => {
no, I mean that you can replace the `return` with just putting parentheses around the object. when defining a closure like this, if you put an expression instead of a block, then it automatically returns the value of the expression. for example, the following two things are equivalent:
```typescript
(a, b) => b-a
```
```typescript
(a, b) => {
    return b-a;
}
```
the only thing is, if what you're returning is an object, you need to wrap it in parentheses in order for the parser to treat it as an object rather than a code block. so the following are equivalent:
```typescript
(a, b) => {
    return {
        key: a,
        value: b,
    }
}
```
```typescript
(a, b) => ({
    key: a,
    value: b,
})
```

2023-04-20 21:30 UTC, purplexa commented on shared/agent/src/providers/bitbucket.ts
> +	role: string; // PARTICIPANT, REVIEWER
right, so rather than hardcoding the strings `"PARTICIPANT"` and `"REVIEWER"` everywhere, you could set the type for `role` to be `BitbucketParticipantRole` and then elsewhere instead of `"PARTICIPANT"` you'd put `BitbucketParticipantRole.Participant` and instead of `"REVIEWER"` you'd put `BitbucketParticipantRole.Reviewer`. it's longer, yes, but it allows the IDE to autocomplete and check that you don't have typos, etc.

2023-04-20 21:37 UTC, reneelpetit commented on shared/agent/src/providers/bitbucket.ts
> +	private _mergeSort(arr: any[]) {
That's definitely easier, but when I do it that way it seems to get out of order.  I'll do some debugging to see if I can figure out why.

2023-04-21 14:24 UTC, dsellarsnr reviewed
Not done with review yet, just want to see what happens when I push the PR comments from codestream.

2023-04-21 14:24 UTC, dsellarsnr commented on shared/agent/src/managers/documentMarkerManager.ts
> +						modifiedAt: +new Date(comment.updated_on),
Use `new Date(comment.created_on).getTime()` instead of the + for better readability

2023-04-21 14:24 UTC, dsellarsnr commented on shared/agent/src/managers/documentMarkerManager.ts
> +				comments.forEach(async (comment: any) => {
Remove the async

2023-04-21 14:36 UTC, dsellarsnr commented on shared/agent/src/providers/bitbucket.ts
>  			);
Yay! So many types 👍

2023-04-21 14:38 UTC, dsellarsnr commented on shared/agent/src/providers/bitbucket.ts
> +			const isViewerCanUpdate = () => {
Intellij recommends this simplification - don't have to use it

```
const isViewerCanUpdate = () => {
				return !!permissions.body.values.find(
					(_: { user: { account_id: string } }) => _.user.account_id === userResponse.account_id
				);
			};
```

2023-04-21 14:54 UTC, dsellarsnr commented on shared/agent/src/providers/bitbucket.ts
> +		let newReviewers: any[] = [];
Get rid of the any

```suggestion
		let newReviewers: BitbucketReviewers[] = [];
```

2023-04-21 14:55 UTC, dsellarsnr commented on shared/agent/src/providers/bitbucket.ts
> +				//@ts-ignore
Remove ts-ignore - not needed

2023-04-21 14:56 UTC, dsellarsnr commented on shared/agent/src/providers/bitbucket.ts
> +		const payload: { reviewers: any[] } = {
Now that newReviewers is typed this can just be

```typescript
const payload = {
	reviewers: newReviewers,
};
```

2023-04-21 15:01 UTC, dsellarsnr commented on shared/agent/src/providers/bitbucket.ts
> +		};
Since newReviewers is typed you don't need the any

```suggestion
		const payload = {
			reviewers: newReviewers ?? [],
		};```

2023-04-21 15:07 UTC, eric-j requested changes

2023-04-21 15:30 UTC, dsellarsnr commented on shared/agent/src/providers/bitbucket.ts
> +	}
Should be able to get rid of all the any and ts-ignore

```suggestion
	private async _getDefaultReviewers(
		fullnameArr: { fullname: string }[],
		usernameResponse: ApiResponse<BitbucketUser>,
		query: string
	): Promise<GetMyPullRequestsResponse[]> {
		let array: BitbucketPullRequests[] = [];
		for (let i = 0; i < fullnameArr.length; i++) {
			const pullrequests = await this.get<BitbucketValues<BitbucketPullRequests[]>>(
				`/repositories/${fullnameArr[i].fullname}/pullrequests?${query}`
			);

			for (let j = 0; j < pullrequests.body.values.length; j++) {
				const PRid = pullrequests.body.values[j].id;
				const individualPRs = await this.get<BitbucketPullRequest>(
					`/repositories/${fullnameArr[i].fullname}/pullrequests/${PRid}`
				);
				if (individualPRs.body.reviewers?.length) {
					const foundSelf = individualPRs.body.reviewers?.find(
						(_: { account_id: string }) => _.account_id === usernameResponse.body.account_id
					);
					if (foundSelf) {
						array.push(pullrequests.body.values[j]);
						array = flatten(array);
					}
				}
			}
		}
		//sort through array so it's in order
		//loop through array and map with the object below
		const setUpArray = this._mergeSort(array);
		const response = this._setUpResponse(setUpArray);
		return response;
	}
```

2023-04-21 15:33 UTC, dsellarsnr commented on shared/agent/src/providers/bitbucket.ts
> +	private async _getRecents(fullnameArr: { fullname: string }[], query: string): Promise<any> {
Fix the `any`

2023-04-21 15:34 UTC, dsellarsnr commented on shared/agent/src/providers/bitbucket.ts
> +				recents.body.values.forEach((repo: any) => {
remove the `any` - don't need it

2023-04-21 15:35 UTC, dsellarsnr commented on shared/agent/src/providers/bitbucket.ts
> +	}
Should be able to fix all the `any`

2023-04-21 15:36 UTC, dsellarsnr commented on shared/agent/src/providers/bitbucket.ts
> +		const array = [];
Fix the `any` on the return and the array

2023-04-21 17:48 UTC, dsellarsnr commented on shared/ui/Stream/OpenPullRequests.tsx
> +						) {
Can get rid of the ! with a null check

```suggestion
if (derivedState.pullRequestQueries &&
							derivedState.pullRequestQueries[key] &&
							Array.isArray(derivedState.pullRequestQueries[key]) &&
							derivedState.pullRequestQueries[key].length > 0
						) {
```

2023-04-21 17:51 UTC, dsellarsnr commented on shared/ui/Stream/OpenPullRequests.tsx
> +					let newObject = {};
Make it a const and give it a type

```suggestion
					const newObject: FetchProviderDefaultPullResponse = {};
```

2023-04-21 17:53 UTC, dsellarsnr commented on shared/ui/Stream/PullRequestCommitsTab.tsx
> +													<Link href={getCommitUrl(commit)} className="monospace">
Excellent refactor

2023-04-21 17:57 UTC, dsellarsnr commented on shared/ui/Stream/PullRequestEditingComment.tsx
> +		if (text == null || text == undefined || text == props.text || text == props.pr.description) {
IntelliJ recommended simplification (double equals covers null and undefind)

```suggestion
		if (text == null || text == props.text || text == props.pr.description) {
```

2023-04-21 18:35 UTC, dsellarsnr commented on shared/ui/Stream/PullRequests/Bitbucket/MergeScreen.tsx
> +	onClose: Function;
Function is the `any` of functions - can type it pretty easily
```suggestion
	onClose: () => void;
```

2023-04-21 18:35 UTC, dsellarsnr commented on shared/ui/Stream/PullRequests/Bitbucket/MergeScreen.tsx
> +	const pr = props;
not used - can probably remove

2023-04-21 18:36 UTC, dsellarsnr commented on shared/ui/Stream/PullRequests/Bitbucket/MergeScreen.tsx
> +	const options = ["merge_commit", "squash", "fast_forward"];
not used - can probably remove?

2023-04-21 18:39 UTC, dsellarsnr commented on shared/ui/Stream/PullRequests/Bitbucket/MergeScreen.tsx
> +	const [mergeMessage, setMergeMessage] = useState("");
Empty string `""` can cause sneakly problems - you have to handle "" in addition to null and undefined - better to use undefined when value not present

```suggestion
  const [mergeMessage, setMergeMessage] = useState<string>();
```

2023-04-21 18:48 UTC, dsellarsnr commented on shared/ui/Stream/PullRequests/Bitbucket/PullRequest.tsx
> +	const _assignState = (pr, src?: string) => {
Can be typed go go along with `useState`

```suggestion
  const _assignState = (pr: FetchThirdPartyPullRequestResponse, src?: string) => {
```

2023-04-21 18:49 UTC, dsellarsnr commented on shared/ui/Stream/PullRequests/Bitbucket/PullRequest.tsx
> +	const [bbRepo, setBbRepo] = useState<any>(EMPTY_HASH);
Should be typed

```suggestion
  const [bbRepo, setBbRepo] = useState<FetchThirdPartyPullRequestRepository>();
```

2023-04-21 18:57 UTC, dsellarsnr commented on shared/ui/Stream/PullRequests/Bitbucket/PullRequest.tsx
> +			(e: any) => {
This is auto-typed - can remove the `any` and it becomes a DidChangeNotification

```suggestion
			(e) => {
```

2023-04-21 18:58 UTC, dsellarsnr commented on shared/ui/Stream/PullRequests/Bitbucket/PullRequest.tsx
> +	const cantCheckoutReason = useMemo(() => {
Not used - can it be removed or maybe needed later?

2023-04-21 19:13 UTC, dsellarsnr commented on shared/ui/Stream/PullRequests/Bitbucket/PullRequestConversationTab.tsx
> +	bbRepo: any;
Not used - can remove it (otherwise would have to fix `any`)

2023-04-21 19:16 UTC, dsellarsnr commented on shared/ui/Stream/PullRequests/Bitbucket/PullRequestConversationTab.tsx
> +			pr: currentPullRequest?.conversations?.repository?.pullRequest! as any, // TODO handle undefined / null
Better temporary fix - keep the type

```suggestion
    pr: currentPullRequest?.conversations?.repository?.pullRequest!,
```

2023-04-21 19:19 UTC, dsellarsnr commented on shared/ui/Stream/PullRequests/Bitbucket/PullRequestReviewButton.tsx
> +	const _assignState = (pr, src?: string) => {
Same fix as other file - give pr a type

2023-04-21 19:45 UTC, dsellarsnr commented on shared/ui/Stream/PullRequests/Bitbucket/PullRequestTimelineItems.tsx
> +	console.warn(pr);
Probably should remove

2023-04-21 19:50 UTC, dsellarsnr commented on shared/ui/store/providerPullRequests/slice.ts
> +								} as any); // TODO
No need to wait - it works without `as any`

2023-04-21 19:50 UTC, dsellarsnr commented on shared/ui/store/providerPullRequests/slice.ts
> +								} as any); // TODO
Remove `as any`

2023-04-21 20:05 UTC, dsellarsnr commented on shared/util/src/protocol/agent/agent.protocol.providers.ts
> +			state: null | string;
Unless there is a really compelling reason, change all the `null | string` in these new types to be more use the typescript optional notation. It requires changing a few lines of code in `butbucket.ts` but it is not too bad

```suggestion
			state?: string;
```

2023-04-21 20:07 UTC, dsellarsnr commented on shared/ui/Stream/PullRequests/Bitbucket/Timeline.tsx
Remove if not using it

2023-04-21 20:08 UTC, dsellarsnr requested changes
Looking good. Almost there!

2023-04-24 18:54 UTC, reneelpetit commented on shared/ui/Stream/PullRequests/Bitbucket/MergeScreen.tsx
> +	const options = ["merge_commit", "squash", "fast_forward"];
the options one isn't used, I'll remove that. The isCloseSourceBranch, isChecked, & mergeError are used though, so I'll keep those.

2023-04-24 20:17 UTC, reneelpetit commented on shared/util/src/protocol/agent/agent.protocol.providers.ts
> +			state: null | string;
the state options that come back from bitbucket are "approved", "changes_requested" or null.  That's why I have it as null | string, because null is a legitimate option there.

2023-05-08 21:20 UTC, merged