Feature/fossa matching
TeamCodeStream/codestream pull request #1706
Opened 2023-08-30 18:05 UTC by reneelpetit

[NR-156018](https://issues.newrelic.com/browse/NR-156018) - in progress

2023-08-30 18:18 UTC, bcanzanella commented on shared/agent/package.json
> +		"test-unit": "npx jest --forceExit --testPathPattern=\"test\\/unit\\/providers\\/fossa\\.spec\\.ts$\" && cd ../util && npm run test",
TODO: this will need to be changed back before merging into develop.

2023-08-30 18:19 UTC, bcanzanella commented on shared/agent/test/unit/providers/fossa.spec.ts
> +		const asdf = await fossa._matchRepoToFossaProject(
does this still now pass? the new logic is looking for a project.id starting with git+ or custom+ and i don't see that in the mock data here.

2023-08-30 18:21 UTC, bcanzanella commented on shared/agent/src/providers/fossa.ts
> +				if (project.id.startsWith("git+")) {
will project.id always start with git+ or custom+? what happens in the unaccounted for `else` case here? we should add (pseudo code) `else { Logger.warn(couldnt parse project, {$project})} } `

2023-08-30 18:46 UTC, reneelpetit commented on shared/agent/test/unit/providers/fossa.spec.ts
> +		const asdf = await fossa._matchRepoToFossaProject(
No, not with the old stuff you created but with the new stuff I created. I just didn't commit it because I wasn't sure if I should. I will now.

2023-08-30 18:47 UTC, reneelpetit commented on shared/agent/src/providers/fossa.ts
> +				if (project.id.startsWith("git+")) {
Dave and Matt said that those were the two possible cases: starting with git+ or starting with custom+.  I'll put in an else just in case there happens to be something else besides those two.

2023-08-30 21:50 UTC, Nameitsattari approved these changes

2023-08-31 16:53 UTC, bcanzanella commented on shared/agent/src/providers/fossa.ts
>  				}
you can further de-dupe some of this with:

```
if (project.id.startsWith("git+")) {
					newUrl = project.id.split("+");
				} else if (project.id.startsWith("custom+")) {
					const idSplit = project.id.split("/");
					const idSliced = idSplit.slice(1);
					newUrl = idSliced.join("/");
				} else {
					Logger.warn("couldn't parse project, ", project);
				}
				if (newUrl) {
					try {
						parsed = await GitRemoteParser.parseGitUrl(`https://${newUrl}`);
					} catch (err) {
						Logger.error(err);
					}
					if (parsed) {
						const [, domain, path] = parsed;
						const folderName = path.split("/").pop();
						if (
							currentRepo.folder.name === folderName &&
							currentRepo.providerGuess &&
							domain.includes(currentRepo.providerGuess)
						) {
							return project;
						}
					}
				}
				```

2023-08-31 16:54 UTC, bcanzanella commented on shared/agent/src/providers/fossa.ts
>  		if (repoId) {
i know this was existing, and possibly subjective, but it will avoid nesting if `if (repoId)` is replaced with `if (!repoId) return undefined;`

2023-08-31 16:54 UTC, bcanzanella commented on shared/agent/test/unit/providers/fossa.spec.ts
> +		const asdf = await fossa._matchRepoToFossaProject(
better const name (below too)

2023-08-31 16:55 UTC, bcanzanella commented on shared/agent/test/unit/providers/fossa.spec.ts
> +	it("matchRepoToFossaProject", async () => {
make these `it` names descriptive of the test they're running. this one for example `matchesRepoToFossaProjectUsingPlusCustom` would be clearer. Same for the others.

2023-08-31 17:00 UTC, bcanzanella requested changes
@reneelpetit have a look at the few comments. thanks.

2023-08-31 17:30 UTC, reneelpetit commented on shared/ui/Stream/CodeAnalyzers/FossaIssues.tsx
> +		? `${vuln.source.version} -> ${vuln.remediation.completeFixDistance}`
yes it's now an object.

2023-08-31 19:05 UTC, bcanzanella commented on shared/agent/src/providers/fossa.ts
>  				}
could even take it further using my other comment with `if (!newUrl) return undefined`

2023-08-31 20:10 UTC, reneelpetit commented on shared/ui/Stream/CodeAnalyzers/FossaIssues.tsx
> +		? `${vuln.source.version} -> ${vuln.remediation.completeFixDistance}`
I changed the typing on agent.protocol.fossa.ts. I had forgotten to commit that in my last commit.

2023-08-31 20:26 UTC, bcanzanella commented on shared/agent/src/providers/fossa.ts
> +							domain.includes(currentRepo.providerGuess)
can a user of fossa use the tool only against github/gitlab/bitbucket? i believe that providerGuess will only ever return github/gitlab/bitbucket so it might not work in self-hosted scenarios where those words aren't in the domain

2023-08-31 20:26 UTC, bcanzanella commented on shared/agent/src/providers/fossa.ts
> +		} else {
`else` is not needed

2023-08-31 20:27 UTC, bcanzanella commented on shared/agent/src/providers/fossa.ts
> +			return;
let's make this clearer `return undefined;`

2023-08-31 20:29 UTC, bcanzanella requested changes
couple last small things!

2023-08-31 21:00 UTC, reneelpetit commented on shared/agent/src/providers/fossa.ts
> +		} else {
@bcanzanella when I get rid of the else I get a typescript error that says Not all code paths return a value and the linter won't let me commit

2023-08-31 21:06 UTC, reneelpetit commented on shared/agent/src/providers/fossa.ts
> +							domain.includes(currentRepo.providerGuess)
it looks like on Fossa.com you can quick import from GitHub, Bitbucket, Bitbucket Server, GitLab and Azure Repos.  Is that what you mean?

2023-08-31 21:28 UTC, bcanzanella commented on shared/agent/src/providers/fossa.ts
> +		} else {
you'll need a `return undefined` at the end.

2023-08-31 21:34 UTC, bcanzanella commented on shared/agent/src/providers/fossa.ts
> +							domain.includes(currentRepo.providerGuess)
yep

2023-08-31 22:10 UTC, merged