NR-56495 Replace incidents with issues and update display
TeamCodeStream/codestream pull request #1798
Opened 2023-10-10 22:00 UTC by reneelpetit

[NR-56495](https://issues.newrelic.com/browse/NR-56495)

Left to do still: 
- add issue clicked event
- check that related entity display for issues works

2023-10-13 18:09 UTC, bcanzanella requested changes

2023-10-13 18:09 UTC, bcanzanella commented on shared/agent/src/providers/newrelic.ts
> +			let id = await this.query<any>(
```
const accountId = this.parseId(request.newRelicEntityGuid)?.accountId;
if (accountId) {
...
}
```

2023-10-13 18:09 UTC, bcanzanella commented on shared/agent/src/providers/newrelic.ts
> +		id: number,
nitpick: call this accountId

2023-10-13 18:09 UTC, bcanzanella commented on shared/agent/src/providers/newrelic.ts
> +				const recentIssuesArray = issueArray.filter(_ => _.closedAt === null);
not sure what `closedAt`'s default value is, but to be certain this works for null & undefined, use `_ => !_.closedAt)`

2023-10-13 22:36 UTC, reneelpetit commented on shared/agent/src/providers/newrelic.ts
> +				const recentIssuesArray = issueArray.filter(_ => _.closedAt === null);
closedAt default is null.  For some reason !_.closedAt wouldn't work, but if I do an || statement it works.

2023-10-16 17:57 UTC, bcanzanella commented on shared/agent/src/providers/newrelic.ts
> +			if (accountId !== null) {
use `if (accountId) {`

2023-10-16 22:22 UTC, eric-j commented on shared/ui/Stream/ObservabilityAlertViolations.tsx
> +		// const riskSeverity = calculateRisk(props.score);
probably can delete these comments

2023-10-16 22:22 UTC, eric-j commented on shared/ui/Stream/ObservabilityAlertViolations.tsx
> +				<span
This is the severity "tag" icon I think.  This could be converted to a styled-component and exported for use around the app if we need to do this again.

2023-10-16 23:18 UTC, merged