fix open in IDE with better remote .git-less options and lowercase st…
TeamCodeStream/codestream pull request #1881
Opened 2023-12-15 17:55 UTC by eric-j

…ring comparisons

2023-12-15 18:49 UTC, purplexa approved these changes

2023-12-18 21:53 UTC, bcanzanella commented on shared/agent/src/git/parsers/remoteParser.ts
> +				results.push({ type: "git", value: `git@${parsed[1]}:${parsed[2]}` });
@eric-j can you add a test to git.spec.ts to handle this new case?

2024-01-03 15:26 UTC, bcanzanella requested changes
one comment from me

2024-01-04 17:02 UTC, reneelpetit approved these changes

2024-01-08 22:12 UTC, merged