Feature/nr 151781
TeamCodeStream/codestream pull request #1885
Opened 2024-01-03 00:52 UTC by reneelpetit

See issues on GH:

Export data has bad header

https://github.com/TeamCodeStream/codestream/issues/1682

Export data corrupt when comment has a comma

https://github.com/TeamCodeStream/codestream/issues/1683

2024-01-03 14:59 UTC, bcanzanella requested changes

2024-01-03 14:59 UTC, bcanzanella commented on shared/ui/Stream/ExportPanel.tsx
> +		let output = [{}];
is it a convention with the library to have an empty object at the 0th position?

2024-01-03 14:59 UTC, bcanzanella commented on shared/ui/Stream/ExportPanel.tsx
> +		return derivedState.codemarks.length ? data : "";
ternary check seems not needed since you have one at line 47.

2024-01-03 14:59 UTC, bcanzanella commented on shared/ui/Stream/ExportPanel.tsx
> +						{derivedState.codemarks.length ? generateCsv() : ""}
no need for ternary check since you have a check inside the method

2024-01-03 14:59 UTC, bcanzanella commented on shared/ui/Stream/ExportPanel.tsx
> +		const data = stringify(output, {
opinion: i'd add some error handling (try/catch) since the user's data is unknown and it's possible something could trigger an error in that library during the stringify.

2024-01-03 14:59 UTC, bcanzanella commented on shared/ui/Stream/ExportPanel.tsx
> +							onClick={() => copy(generateCsv())}
seems like the output of generateCsv() could live in a local state variable? that way you don't have to re-run it. i'll wait for others to see if they agree on that.

2024-01-03 15:14 UTC, dsellarsnr commented on shared/ui/Stream/ExportPanel.tsx
> +	function generateCsv() {
Whenever you can you should have views only doing view things - should move generateCsv into a separate file and make sure it doesn't import anything from react so that it is abstracted away and can stand on it's own.

2024-01-06 01:26 UTC, reneelpetit commented on shared/ui/Stream/ExportPanel.tsx
> +	function generateCsv() {
is there any particular file I should put generateCsv in?  Or just make one called generateCsv?

2024-01-08 20:37 UTC, dsellarsnr approved these changes

2024-01-09 00:16 UTC, merged