Feature/nr 220413: Issues with "codestream/codemarks/codemark displayed" event
TeamCodeStream/codestream pull request #1951
Opened 2024-02-09 20:38 UTC by reneelpetit

https://new-relic.atlassian.net/browse/NR-220413
https://new-relic.atlassian.net/browse/NR-220932

2024-02-09 20:54 UTC, bcanzanella commented on shared/ui/Stream/SearchResult.tsx
> +		const session = store.getState().session;
change to `const { users, session }= store.getState();` then access `users` and `session` from that.

2024-02-09 20:56 UTC, bcanzanella commented on shared/ui/Stream/SearchResult.tsx
> +		const currentUser = session.userId || users[session.userId!];
`users[session.userId!]` returns a userId or a userObject? if it's an object you'll need to get the id -- i suspect the `toString()` below was an attempt around that...

2024-02-09 20:56 UTC, bcanzanella commented on shared/ui/index.tsx
> +			meta_data: `codemark_location: source_file`,
make that `source_file` come through as an optional argument from the Notification

2024-02-09 20:57 UTC, bcanzanella commented on vscode/src/commands.ts
>  		return Container.sidebar.openCodemark(args.codemarkId, options);
`Container.sidebar.openCodemark(args.codemarkId, {source: "source_file", ...options });`

2024-02-09 20:57 UTC, bcanzanella commented on shared/ui/index.tsx
> +			meta_data: `codemark_location: source_file`,
(see below)

2024-02-09 20:58 UTC, bcanzanella commented on shared/ui/Stream/ActivityPanel.tsx
> +												derivedState.currentUserId!
is currentUserId guaranteed here? i see the removal of the empty string fallback...

2024-02-09 21:40 UTC, reneelpetit commented on shared/ui/Stream/SearchResult.tsx
> +		const currentUser = session.userId || users[session.userId!];
I only saw a userId, I didn't know it could also be a userObject. I'll change it, thanks

2024-02-09 21:45 UTC, bcanzanella commented on shared/ui/Stream/SearchResult.tsx
> +		const currentUser = session.userId || users[session.userId!];
let me clarify... `users[session.userId!]` returns an `object` not a string. you would need to do `users[session.userId!]?.id`

2024-02-09 21:47 UTC, bcanzanella commented on shared/ui/index.tsx
> +			meta_data: `codemark_location: source_file`,
it does in the current use-case, but anyone can trigger a `ShowCodemarkNotificationType` notification, not just things that come from source code.

2024-02-12 18:42 UTC, bcanzanella commented on shared/ui/index.tsx
> +export interface SourceOptions {
nice!!!

2024-02-12 18:44 UTC, bcanzanella requested changes
see one comment

2024-02-12 18:44 UTC, bcanzanella commented on shared/ui/index.tsx
> +		const currentUser = session.userId || users[session.userId!];
this should be:

`const currentUser = session.userId || users[session.userId!].id`;

(not in my IDE, so please double check)

2024-02-12 18:45 UTC, reneelpetit commented on shared/ui/index.tsx
> +		const currentUser = session.userId || users[session.userId!];
oh weird, I swear I already did that ....

2024-02-12 18:49 UTC, merged