Feature/link to logs from code error
TeamCodeStream/codestream pull request #2045
Opened 2024-03-15 19:26 UTC by reneelpetit

2024-03-18 21:11 UTC, reneelpetit commented on shared/webviews/editor/App.tsx
I'm not sure what happened here exactly -- I think maybe we've deleted App.tsx?

2024-03-18 21:25 UTC, CalvinAllen requested changes
See previous comments

2024-03-18 21:42 UTC, reneelpetit commented on shared/webviews/editor/App.tsx
great, thanks!

2024-03-18 21:43 UTC, reneelpetit commented on shared/ui/ipc/host.protocol.ts
> +	params?: {};
Oh yeah, Lexa and I were talking about how maybe in the future if we need to add more things we should use a params and then put it all under that. That's why it's there. I can take it out

2024-03-18 22:11 UTC, reneelpetit commented on shared/ui/Stream/APMLogging/APMLogSearchPanel.tsx
> +			{
oh yeah ... that's much easier :) Thanks

2024-03-19 13:39 UTC, CalvinAllen approved these changes

2024-03-19 14:09 UTC, bcanzanella requested changes

2024-03-19 14:09 UTC, bcanzanella commented on shared/ui/Stream/CodeError/index.tsx
> +								e.preventDefault(), openLogs();
should be:

```
e.preventDefault();
openLogs();
```

2024-03-19 14:09 UTC, bcanzanella commented on shared/ui/Stream/CodeError/index.tsx
> +			ide: {},
fill `ide` out, check out other usages of OpenEditorViewNotificationType

2024-03-19 14:09 UTC, bcanzanella commented on shared/util/src/protocol/agent/agent.protocol.providers.ts
> +	id?: string;
what's this `id` ?

2024-03-19 15:21 UTC, dsellarsnr commented on shared/agent/src/providers/newrelic/errors/observabilityErrorsProvider.ts
> +						traceId: returnTraceId || errorTraceResponse.actor.account.nrql.results[0].traceId,
`|| errorTraceResult.traceId` to keep it brief

2024-03-19 15:28 UTC, dsellarsnr approved these changes
Just the 1 comment and weird issue posted in Slack

2024-03-20 22:28 UTC, reneelpetit commented
moved to https://github.com/TeamCodeStream/codestream/pull/2050  due to rebase changes

2024-03-20 22:28 UTC, closed without merging