Service search
TeamCodeStream/codestream pull request #2143
Opened 2024-05-09 19:24 UTC by eric-j

https://new-relic.atlassian.net/browse/NR-238700

2024-05-09 20:47 UTC, eric-j commented on shared/ui/src/__tests__/Stream/Observability.test.tsx
> +	// @TODO - Get resize-observer polyfill working so we can test this use case.
This needs to be addressed in a separate ticket

2024-05-13 14:13 UTC, bcanzanella commented on shared/agent/src/providers/newrelic/errors/observabilityErrorsProvider.ts
> +							remote: "test", //application.urlValue!,  not sure what to do with this
TODO?

2024-05-13 14:15 UTC, bcanzanella commented on shared/agent/src/providers/newrelic/goldenSignals/goldenSignalsProvider.ts
> +	async getEntityFromGuid(entityGuid: string): Promise<GetEntityFromGuid> {
name doesn't related to inner query. should this live in observabilityErrorsProvider.ts?

2024-05-13 14:17 UTC, bcanzanella commented on shared/ui/Stream/TransactionSpanPanel.tsx
> +						meta_data_3: "entry_point: open_in_ide",
is that meta_data_3 legit? (open_in_ide in particular)

2024-05-13 14:19 UTC, bcanzanella commented on shared/ui/Stream/RepositoryAssociatorServiceSearch.tsx
> +				for (const repo of response.repositories) {
can this be consolidated with what's in RepositoryAssociator?

2024-05-13 14:21 UTC, bcanzanella commented on shared/ui/Stream/ObservabilityServiceSearch.tsx
> +							alertSeverityColor={alertSeverityColor}
or just a `{...props}` ?

2024-05-13 14:23 UTC, bcanzanella requested changes
couple of comments

2024-05-15 14:40 UTC, eric-j commented on shared/agent/src/providers/newrelic/errors/observabilityErrorsProvider.ts
> +							remote: "test", //application.urlValue!,  not sure what to do with this
Will update, I believe this can be empty

2024-05-15 15:07 UTC, eric-j commented on shared/ui/Stream/RepositoryAssociatorServiceSearch.tsx
> +				for (const repo of response.repositories) {
they are different enough to where I wanted to keep them as two separate components, but this for loop could possibly go in a util function shared between them.

2024-05-15 15:33 UTC, eric-j commented on shared/agent/src/providers/newrelic/goldenSignals/goldenSignalsProvider.ts
> +	async getEntityFromGuid(entityGuid: string): Promise<GetEntityFromGuid> {
deleted this and used logic from entityProvider, good call

2024-05-15 15:47 UTC, eric-j commented on shared/ui/Stream/RepositoryAssociatorServiceSearch.tsx
> +				for (const repo of response.repositories) {
Digging into this I would rather leave them as two separate functions.

2024-05-15 18:15 UTC, bcanzanella commented on shared/ui/Stream/ObservabilityServiceSearch.tsx
> +	const observabilityServiceEntityProps = {
maybe we could benefit from using React contexts in order to limit the number of props deeply nested components need? @dsellarsnr @eric-j @purplexa  ?

2024-05-15 18:15 UTC, bcanzanella approved these changes

2024-05-15 18:26 UTC, eric-j commented on shared/ui/Stream/ObservabilityServiceSearch.tsx
> +	const observabilityServiceEntityProps = {
That's a good idea:
https://react.dev/learn/passing-data-deeply-with-context

2024-06-07 14:26 UTC, merged