Support protocol handling for "Start Work" from the chrome extension
TeamCodeStream/codestream pull request #271
Opened 2020-09-06 05:19 UTC by ppezaris

**This PR Addresses:**  
[chrome & firefox PR extension](https://trello.com/c/Mx5sA7uZ/4649-chrome-firefox-pr-extension)

2020-09-07 04:55 UTC, ppezaris commented
i changed the generic provider connection to make it possible to use it w/trello as well -- not sure if this is a good idea or not.

2020-09-07 14:34 UTC, ppezaris commented
![](https://github.trello.services/images/mini-trello-icon.png) [Trello powerup to "start work"](https://trello.com/c/3aiOcTJY/4276-trello-powerup-to-start-work)

2020-09-09 16:43 UTC, bcanzanella commented on shared/agent/src/providers/github.ts
> +	async setAssigneeOnIssue(request: { issueId: string; assigneeId: string; onOff: boolean }) {
test

2020-09-11 13:48 UTC, bcanzanella requested changes
looks good. this will need to be rebased from dev before merging. i'll check it out

2020-09-11 13:48 UTC, bcanzanella commented on shared/ui/index.tsx
> +									store.dispatch(setStartWorkCard(card));
i added a `clearCurrentPullRequest` for this

2020-09-11 13:48 UTC, bcanzanella commented on shared/ui/index.tsx
> +												store.dispatch(setStartWorkCard(issue));
i added a `clearCurrentPullRequest` for this

2020-09-11 14:00 UTC, bcanzanella commented on shared/ui/index.tsx
> +												store.dispatch(setStartWorkCard(issue));
i updated it

2020-09-11 14:00 UTC, bcanzanella commented on shared/ui/index.tsx
> +									store.dispatch(setStartWorkCard(card));
i updated it

2020-09-11 14:04 UTC, merged