handle legacy GHE servers
TeamCodeStream/codestream pull request #313
Opened 2020-11-03 00:57 UTC by bcanzanella

2020-11-03 18:44 UTC, marcelofarias commented on shared/agent/src/providers/github.ts
> +					${this._transform(`[isDraft:>=2.21.0]`)}
love it

2020-11-03 18:46 UTC, marcelofarias commented on shared/agent/src/providers/github.ts
>  		return true;
I believe we are missing the actual API call here

2020-11-03 18:48 UTC, marcelofarias commented on shared/agent/src/providers/github.ts
>  		return true;
We might be missing the actual API call here as well

2020-11-03 18:52 UTC, marcelofarias requested changes
I think you inadvertently removed a couple `transform` calls

2020-11-03 18:57 UTC, bcanzanella commented
&gt; I think you inadvertently removed a couple `transform` calls<br>I sure did... fixing now.

2020-11-04 14:05 UTC, bcanzanella commented
can you take a final look at this @mfarias&nbsp;?

2020-11-04 16:31 UTC, marcelofarias approved these changes

2020-11-04 16:31 UTC, merged

2020-11-04 19:25 UTC, bcanzanella commented on shared/agent/src/providers/github.ts
>  					  pullRequest {
1

2020-11-04 19:39 UTC, bcanzanella commented on shared/agent/src/providers/github.ts
>  		this._pullRequestCache.delete(request.pullRequestId);
2

2020-11-04 19:40 UTC, bcanzanella commented
1

```
const query = `query pr($owner:String!, $repo:String!) {
				repository(name: $repo, owner: $owner${cursor ? `, after: $cursor` : ""}) {
					pullRequests(states: [OPEN, MERGED], first: 100, orderBy: { field: UPDATED_AT, direction: DESC }) {
						totalCount
						pageInfo {
							startCursor
							endCursor
							hasNextPage
```
								
[shared/agent/src/providers/github.ts](https://github.com/teamcodestream/codestream/blob/595c2878bcee4e113dc778e802ec5b6e926b9ac3/shared/agent/src/providers/github.ts#L3500-L3507) (Lines 3500-3507)

2020-11-04 19:53 UTC, bcanzanella commented on shared/agent/src/providers/github.ts
>  					  pullRequest {
a

2020-11-04 20:01 UTC, bcanzanella commented on shared/agent/src/providers/github.ts
>  					__typename
1

2020-11-04 20:01 UTC, bcanzanella commented
2

```
g()
	getPullRequestDocumentMarkers({
		uri,
		repoId,
		streamId
	}: {
```
								
[shared/agent/src/providers/github.ts](https://github.com/teamcodestream/codestream/blob/595c2878bcee4e113dc778e802ec5b6e926b9ac3/shared/agent/src/providers/github.ts#L667-L672) (Lines 667-672)

2020-11-04 20:01 UTC, bcanzanella commented on shared/agent/src/providers/github.ts
3 empty lines around

2020-11-04 20:02 UTC, bcanzanella commented on shared/agent/src/providers/github.ts
> +									_.indexOf(".query") === -1
4

2020-11-04 20:02 UTC, bcanzanella commented on shared/agent/src/providers/github.ts
> +	 * @memberof GitHubProvider
5

2020-11-04 20:02 UTC, bcanzanella commented on shared/agent/src/providers/github.ts
>  import { Arrays, Functions, log, lspProvider, Strings } from "../system";
6

2020-11-04 20:07 UTC, bcanzanella commented on shared/agent/src/providers/github.ts
>  					  pullRequest {
a

2020-11-04 20:16 UTC, bcanzanella commented on shared/agent/src/providers/github.ts
>  					__typename
a

2020-11-04 20:20 UTC, bcanzanella commented
a

```
	`mutation CreatePullRequest($repositoryId:ID!, $baseRefName:String!, $headRefName:String!, $title:String!, $body:String!) {
					__typename
					createPullRequest(input: {repositoryId: $repositoryId, baseRefName: $baseRefName, headRefName: $headRefName, title: $title, body: $body}) {
					  pullRequest {
							number,
							id,
							url,
							title
						}
```
								
[shared/agent/src/providers/github.ts](https://github.com/teamcodestream/codestream/blob/595c2878bcee4e113dc778e802ec5b6e926b9ac3/shared/agent/src/providers/github.ts#L704-L712) (Lines 704-712)

2020-11-04 20:24 UTC, bcanzanella commented
4

```
`mutation CreatePullRequest($repositoryId:ID!, $baseRefName:String!, $headRefName:String!, $title:String!, $body:String!) {
					__typename
					createPullRequest(input: {repositoryId: $repositoryId, baseRefName: $baseRefName, headRefName: $headRefName, title: $title, body: $body}) {
					  pullRequest {
							number,
							id,
							url,
							title
						}
					}
```
								
[shared/agent/src/providers/github.ts](https://github.com/teamcodestream/codestream/blob/595c2878bcee4e113dc778e802ec5b6e926b9ac3/shared/agent/src/providers/github.ts#L704-L713) (Lines 704-713)

2020-11-04 21:15 UTC, bcanzanella commented on shared/agent/src/providers/github.ts
>  					__typename
2

2020-11-04 21:16 UTC, bcanzanella commented on shared/agent/src/providers/github.ts
>  			// 		}
a

2020-11-04 21:16 UTC, bcanzanella commented on shared/agent/src/providers/github.ts
>  			// 		  clientMutationId
a

2020-11-04 21:17 UTC, bcanzanella commented on shared/agent/src/providers/github.ts
>  					}
a

2020-11-04 22:18 UTC, bcanzanella commented on shared/agent/src/providers/github.ts
> +			// const query = `mutation UpdateDraft($pullRequestId:ID!, $isDraft:Boolean!) {
1

2020-11-04 22:22 UTC, bcanzanella commented on shared/agent/src/providers/github.ts
>  			// 		}
g

2020-11-04 22:26 UTC, bcanzanella commented on shared/agent/src/providers/github.ts
>  			// 		}
a

2020-11-04 22:27 UTC, bcanzanella commented on shared/agent/src/providers/github.ts
>  			// 		}
a

2020-11-05 14:17 UTC, bcanzanella commented on shared/agent/src/providers/github.ts
> +import { SessionContainer } from "../container";
a

2020-11-05 14:17 UTC, bcanzanella commented on shared/agent/src/providers/github.ts
> +import { CSGitHubProviderInfo, CSRepository } from "../protocol/api.protocol";
a