https://trello.com/c/Dz3ZUwNU/5091-create-pr-to-main-repo-from-fork
TeamCodeStream/codestream pull request #330
Opened 2020-11-18 02:35 UTC by ppezaris

2020-11-18 02:36 UTC, ppezaris commented
We still have an issue w/r/t detecting whether an existing PR exists for a given base/head selection... we're always checking the local repo for the PR, even if you select a different repo as the base.

2020-11-18 16:08 UTC, marcelofarias requested changes

2020-11-18 16:08 UTC, marcelofarias commented on shared/agent/src/managers/reviewsManager.ts
> +				Logger.log(`Couldn't find branchRepot for ${repo.path} and ${headRefName}`);
typo

2020-11-18 16:08 UTC, marcelofarias commented on shared/agent/src/providers/github.ts
> +					true
Why the hard-coded domain?

2020-11-18 16:08 UTC, marcelofarias commented on shared/agent/src/providers/github.ts
> +				};
Not sure if we really want to return the grandparent in this case. Arguably both use cases are valid when you have a multi-level forking hierarchy, but I guess (and this is just a guess) that sending a PR to the immediate parent is the most common use case.

2020-11-18 16:38 UTC, bcanzanella commented on shared/agent/src/providers/github.ts
> +					true
Came from some code i wrote. i have a card to fix this. the fn argument assumes remote a full uri since it uses a URI.parse later on. i'll change it to be a remotePath rather than a `remote`

2020-11-18 18:42 UTC, bcanzanella commented on shared/agent/src/protocol/agent.protocol.reviews.ts
> +	providerRepositoryId?: string; // for use across forks
`/* this style comment will show a tool tip in the ide */` (line 372)

2020-11-18 18:42 UTC, bcanzanella commented on shared/agent/src/providers/github.ts
>  			}
nice idea (line 711-723)

2020-11-18 18:43 UTC, bcanzanella commented on shared/agent/src/providers/provider.ts
> +	remote: string; // to look up the repo ID on the provider
same as other comment (lines 949-950)

2020-11-18 18:49 UTC, bcanzanella commented on shared/ui/Stream/CreatePullRequestPanel.tsx
> +				// is there a way to fetch diffs across forks w/provider APIs?
no, i'll make a card (line 550) https://trello.com/c/AovC3uSp/5222-fetchfileschanged-for-forked-repos

2020-11-19 17:39 UTC, ppezaris commented on shared/agent/src/providers/github.ts
> +				};
this isn't the grandparent... just the parent.

2020-11-19 17:41 UTC, ppezaris commented on shared/agent/src/providers/github.ts
>  			}
sorry but not quite sure what "nice idea" means here...

2020-11-19 17:43 UTC, bcanzanella commented on shared/agent/src/providers/github.ts
>  			}
sorry, that was just a test

2020-11-20 16:03 UTC, bcanzanella commented
@marcelofarias is this ready to merge in?

2020-11-23 14:55 UTC, merged