Feature/updated pr doesnt2
TeamCodeStream/codestream pull request #635
Opened 2021-06-22 19:20 UTC by patrick-morgan

Added functionality so that when a user changes an item on the pullrequestconversationtab pane we refresh the user's prs asynchronously so that when they exit out of the pr their pull requests are up to date for each query listed.

Currently using a timeout to delay the refreshing of the prs long enough for GH's servers to process the update (e.g. adding a label, assignee, etc), the timeout is set to 2 seconds but this means that sometimes the data will be refreshed too early and not be displayed properly. There is surely a better way to do this.

2021-06-23 14:38 UTC, bcanzanella requested changes
Couple comments

2021-06-23 14:38 UTC, bcanzanella commented on shared/ui/Stream/OpenPullRequests.tsx
> +			// update store
is this comment old, or is this a real TODO?

2021-06-23 14:38 UTC, bcanzanella commented on shared/ui/store/providerPullRequests/reducer.ts
> +		// case ProviderPullRequestActionsTypes.ClearPullRequestError: {
was this removed for testing?

2021-06-23 14:38 UTC, bcanzanella commented on shared/ui/store/providerPullRequests/reducer.ts
> +					pullRequests: newState,
nit pick on these trailing commas (there are a bunch in this file). if you have the esbenp.prettier-vscode extension setup it should remove them all for you. (I like to enable format on save)


![Screen Shot 2021-06-23 at 10.25.33 AM.png](https://usercontent.codestream.com/5bbe4963acc6981860b78f03/9663c73f-0070-4586-ba60-c48c83c81ef0/Screen%20Shot%202021-06-23%20at%2010.25.33%20AM.png)

2021-06-23 14:38 UTC, bcanzanella commented on shared/ui/Stream/PullRequestConversationTab.tsx
> +				if (queries) {
can this be `derivedState.pullRequestQueries`?

2021-06-23 14:38 UTC, bcanzanella commented on shared/ui/Stream/PullRequestConversationTab.tsx
> +					const providerQuery: PullRequestQuery[] = queries[connectedProvider.id];
there are a few other spots where we're defaulting the queries with `|| defaultQueries[connectedProvider.id]]` and i think we should do that here too. (queries don't exist in a user object if they haven't modified them)

2021-06-24 18:28 UTC, patrick-morgan commented on shared/ui/Stream/OpenPullRequests.tsx
> +			// update store
old comment

2021-06-24 18:29 UTC, patrick-morgan commented on shared/ui/store/providerPullRequests/reducer.ts
> +		// case ProviderPullRequestActionsTypes.ClearPullRequestError: {
had  it moved down there for testing, it is still above not commented out. Deleted the commented out code

2021-06-24 18:30 UTC, patrick-morgan commented on shared/ui/store/providerPullRequests/reducer.ts
> +					pullRequests: newState,
linted file 👍

2021-06-24 19:00 UTC, patrick-morgan commented on shared/ui/Stream/PullRequestConversationTab.tsx
> +					const providerQuery: PullRequestQuery[] = queries[connectedProvider.id];
Good catch, changed this to use defaultQueries. If we want to store defaultQueries in the store then I can add that too

2021-06-24 19:22 UTC, bcanzanella commented on shared/ui/store/providerPullRequests/reducer.ts
> +		// case ProviderPullRequestActionsTypes.ClearPullRequestError: {
ah gotcha, thanks. that's what i get for starting this review on gh.com (no context of the whole file) :/

2021-06-24 19:25 UTC, bcanzanella commented on shared/ui/Stream/PullRequestConversationTab.tsx
> +					const providerQuery: PullRequestQuery[] = queries[connectedProvider.id];
i think what you have will work!

2021-06-24 19:26 UTC, bcanzanella approved these changes

2021-06-24 19:26 UTC, patrick-morgan commented on shared/ui/Stream/PullRequestConversationTab.tsx
> +				if (queries) {
yep

2021-06-24 19:26 UTC, merged