Gitlab mr issues
TeamCodeStream/codestream pull request #717
Opened 2021-09-15 23:46 UTC by patrick-morgan

Fixed default setting for deleting source branch, and added squash_option support for Gitlab MRs.

2021-09-16 15:22 UTC, bcanzanella requested changes

2021-09-16 15:22 UTC, bcanzanella commented on shared/ui/Stream/PullRequests/GitLab/MergeBox.tsx
> +									disabled=" "
remove the "disabled" field

2021-09-16 15:22 UTC, bcanzanella commented on shared/agent/src/protocol/agent.protocol.gitlab.ts
> +		squashOption: string;
if there is a known enum of values here, you can use those as the type:

`squashOption: "default_on" | "always" | "never"`

2021-09-16 15:22 UTC, bcanzanella commented on shared/agent/src/providers/gitlab.ts
> +				squash_option: string;
same w/r/t the squash type not being a string. you could create a TypeScript type that has all the enums (so that it's reusable) and can be reused here.

2021-09-16 15:22 UTC, bcanzanella commented on shared/ui/Stream/PullRequests/GitLab/MergeBox.tsx
> +						{derivedState.prRoot && derivedState.prRoot.project.squashOption === "always" ? (
i think you could wrap this whole section with a `derivedState.prRoot` check if you'd like to minimize multiple checks

```
{derivedState.prRoot && (
   <>
    {derivedState.prRoot.project.squashOption === "always" ? () : ()}
    {derivedState.prRoot.project.squashOption !== "never" && ()}
   </>
)}
```

2021-09-24 17:53 UTC, patrick-morgan commented on shared/ui/Stream/PullRequests/GitLab/MergeBox.tsx
> +									disabled=" "
without that the checkbox will appear to be clickable. I added the disabledEmpty field so that now the checkbox will be disabled but there won't display any text after that would mess up the formatting

2021-09-24 23:12 UTC, bcanzanella approved these changes

2021-09-24 23:12 UTC, merged