PR UX, diffs in sidebar
TeamCodeStream/codestream pull request #946
Opened 2022-04-04 15:30 UTC by eric-j

New PR UX, JB inline commenting

2022-04-12 17:17 UTC, eric-j commented on shared/ui/Stream/OpenPullRequests.tsx
> +	.files-changed-list-dropdown {
This is just at test comment... testing PRs on a PR for PRs... woah

2022-04-12 18:02 UTC, eric-j commented on shared/ui/Stream/OpenPullRequests.tsx
>  		}
testtestteststet

2022-04-12 18:06 UTC, eric-j commented on shared/ui/Stream/OpenPullRequests.tsx
>  	const [prError, setPrError] = React.useState("");
another test comment

2022-04-12 18:06 UTC, eric-j commented on shared/ui/Stream/OpenPullRequests.tsx
> +			// depending on the user's preference
and another

2022-04-12 18:09 UTC, eric-j commented on shared/ui/Stream/OpenPullRequests.tsx
> +	const fetchOnePR = async (providerId: string, pullRequestId: string, message?: string) => {
test

2022-04-18 17:37 UTC, eric-j commented on shared/ui/Stream/OpenPullRequests.tsx
>  		}
test 2

2022-04-18 18:45 UTC, eric-j commented on shared/ui/Stream/OpenPullRequests.tsx
>  		}
test 3

2022-04-18 21:04 UTC, eric-j commented on shared/ui/Stream/OpenPullRequests.tsx
> +	.files-changed-list-dropdown {
testtttt

2022-04-18 21:04 UTC, eric-j commented on shared/ui/Stream/OpenPullRequests.tsx
> +	.files-changed-list-dropdown {
test 2222

2022-04-25 16:09 UTC, eric-j commented on shared/ui/Stream/Review/ChangesetFile.tsx
> +	chevron?: any;
test

2022-04-28 14:35 UTC, bcanzanella requested changes
couple tiny things, but this looks incredible, great work!

2022-04-28 18:15 UTC, bcanzanella approved these changes
this is killer! nice job!

2022-04-28 18:16 UTC, bcanzanella commented
we'll leave all this in the branch for now... can send beta users vsix from this branch in TC.

2022-05-03 18:07 UTC, eric-j commented on shared/ui/store/context/reducer.ts
> +								groupIndex: action.payload?.groupIndex
test

2022-05-03 18:09 UTC, eric-j commented on shared/ui/store/context/actions.ts
> +	action(ContextActionsType.SetCurrentPullRequest, {
hello world

2022-05-11 22:23 UTC, eric-j commented on jb/src/main/kotlin/editor/EditorComponentInlaysManager.kt
> +import java.awt.Dimension
asd

2022-05-16 19:40 UTC, cstryker reviewed
FYI, i'm sort of abstaining from this review since it's more or less out of my wheelhouse ... i can still review though, if needed

2022-05-24 16:29 UTC, merged