VS C# Code Level Metrics
TeamCodeStream/codestream pull request #998
Opened 2022-06-01 17:30 UTC by CalvinAllen

<sup> Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)</sup>

2022-06-03 20:41 UTC, CalvinAllen commented
@bcanzanella I think this is ready to go - I did do some cleanup / etc.

2022-06-04 15:36 UTC, bcanzanella commented on vs/publishManifest.json
> -{
i think we need this file... pretty sure it's needed for our CI/CD deploy to marketplace pipeline

2022-06-04 15:40 UTC, CalvinAllen commented on vs/publishManifest.json
> -{
Let me double check this, I think there were two of them - the other in the publish folder maybe?

2022-06-04 15:41 UTC, bcanzanella commented on vs/src/CodeStream.VisualStudio.Shared/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.0.0.0")]
update these to the current version (13.0.1.0)

2022-06-04 15:41 UTC, bcanzanella commented on vs/src/CodeStream.VisualStudio.CodeLens/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.0.0.0")]
update these to the current version (13.0.1.0)

2022-06-04 15:45 UTC, bcanzanella commented on vs/src/CodeStream.VisualStudio/UI/ToolWindows/CodeLevelMetricsDetails.xaml.cs
> +								Log.Error(ex, $"{nameof(AddCodemarkCommandBase)} event");
nit pick on the `nameof`

2022-06-04 15:46 UTC, bcanzanella requested changes
couple of small changes, but otherwise looks awesome!

2022-06-05 01:27 UTC, CalvinAllen commented on vs/publishManifest.json
> -{
You're right - the *other* files are duplicates / wrong.

2022-06-05 01:32 UTC, CalvinAllen commented on vs/src/CodeStream.VisualStudio/UI/ToolWindows/CodeLevelMetricsDetails.xaml.cs
> +								Log.Error(ex, $"{nameof(AddCodemarkCommandBase)} event");
Fixed - also found an issue with that traced back to the RequestCodeReviewCommand

2022-06-05 01:32 UTC, CalvinAllen commented
@bcanzanella All that should be resolved now

2022-06-06 15:17 UTC, bcanzanella approved these changes
🚀 🚀 🚀

2022-06-06 15:23 UTC, merged